### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by FabianKoestring** [laminas/laminas-cache-storage-adapter-redis#23]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary
In `laminas/laminas-cache` v2 i had an own implementation of `Laminas\Cache\Storage\Adapter\Redis` which only adds a function like `ping()`. I called it `isAvailable()`. What are your thoughts on adding this functionality.

```php
public function ping(): bool
{
    $redis = $this->getRedisResource();
    try {
        return $redis->ping() === "+PONG"
    } catch (RedisResourceException $e) {
        throw new Exception\RuntimeException($redis->getLastError(), $e->getCode(), $e);
    }

    return false;
}
```

I could create a pull request for this!

**Comment by boesing** [comment]
@FabianKoestring That sounds like a useful extension, yes!

Lets first rubber duck a little bit before starting to work on concrete implementation.

### Implementation

I think, some kind of `PingableInterface` (next to those `TaggableInterface`, etc.) would make sense regarding this, what do you think about it? This way, we can add the interface to other adapters as well.

### Do you have some more information on how you do need this functionality?
- e.g. are you using it in long-running processes?
- what do you do with a `false` return value?

### RuntimeException
Do we really need to throw a runtime exception? Why not returning `false` here?

### Reconnection?
In case `false` is being returned, would it make sense to have some kind of `reconnection` functionality?


----

I would really love to get some more insights on this - but overall: this would be a great addition to the `laminas-cache` component.

**Comment by FabianKoestring** [comment]
@boesing Hey there! For now i removed that function and use `laminas/laminas-cache` v3. We simply implemented that function to run the application without running cache implementation. Before we read from cache or write to cache we test if the cache (redis) is available. if not - no problem. Run without cache. 🤷‍♂️

**Comment by boesing** [comment]
@FabianKoestring Usually, there should be no real reason to verify if the cache is available or not.
There might be long-running processes which do need to re-connect to the cache adapter due to possible timeouts but until you are just running your application "the usual way" (LAMP or whatever), there should be no need due to the fact that on the very first cache access (either read or write), the adapter will create a fresh connection (depending on the configuration).

In combination with the `ExceptionHandler`-[Plugin](https://docs.laminas.dev/laminas-cache/v3/storage/plugin/#the-exceptionhandler-plugin), you can disable exceptions at all and thus, when trying to read, `null` is returned (as the cache would be missing) or `false` is returned (when trying to store something).

Usually, we (in my company) do not really care if a `StorageInterface#setItem` returned `true` or `false` and since a cache should not be considered as a persistence layer, a cache-miss should be handleable by an application.

----

So from your last message, this feature is no longer of interest? I'll close here for now - if you want to work on this, please let me know. Happy to help wherever I can.
