### ISSUE TITLE
Add support for ext-redis ^6.0

### ISSUE THREAD

**Issue by cooperaj** [laminas/laminas-cache-storage-adapter-redis#78]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes/no

#### Summary

Support for the newly released ext-redis 6.0.0.

**Comment by boesing** [comment]
Could you link the release notes of v6? 

We have to see if its already provided by sury so that we can verify compatibility in CI. 

Afaik, we are not testing (yet) specific versions of extensions. I'll see if I can add some magic to the CI so that we can run Integration tests in all supported extension versions. 

Yah, seems that sury is not providing v6 yet:
https://packages.sury.org/php/pool/main/p/php-redis/


Therefore, current Integration tests are only executed with 5.3.7
I'll see how I can ensure testing multiple versions.

**Comment by cooperaj** [comment]
https://pecl.php.net/package-changelog.php?package=redis&release=6.0.0

**Comment by InvisibleSmiley** [comment]
Sury includes ext-redis 6 since yesterday.

**Comment by TuningYourCode** [comment]
Also sury repo does only contain version 6.0.0 and no longer the old version 5.3.7 any longer (for debian bullseye and php8.1 - not sure about other)

Luckily we still had the old deb in our apt proxy :)

But expect that the next days a few build systems will break - at least if they install the redis extension from sury repo or have auto updates enabled :)

**Comment by cooperaj** [comment]
>But expect that the next days a few build systems will break

Yep, that's what prompted this issue. We build from source in our containers using mlocati/php-extension-installer and hadn't pinned ext-redis to 5.x. We have now.

**Comment by tim-hitchins-ekkosense** [comment]
@cooperaj Yep, my build just broke too - thanks for pointing to mlocati/php-extension-installer, that looks really helpful!

**Comment by boesing** [comment]
Can s1 provide a patch? will merge it once passing CI. updating the constraint in composer should suffice.

Will create an issue afterwards to extend the CI Pipeline to further check all supported extension versions 👍🏻

**Comment by boesing** [comment]
Create a patch, please follow that PR for more details
